# Generated by Django 3.2.6 on 2021-09-28 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descirption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='descirption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='descirption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='descirption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usertrackbridge',
            name='progress',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default_avatar.png', upload_to='user_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
