# Generated by Django 3.2.6 on 2021-08-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Infrastructure Engineer', 'Infrastructure Engineer')], max_length=50),
        ),
    ]
