# Generated by Django 3.2.7 on 2021-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('description', models.TextField()),
                ('members', models.JSONField()),
                ('business_document', models.FileField(upload_to='')),
                ('technical_document', models.FileField(upload_to='')),
            ],
        ),
    ]
