# Generated by Django 3.2.6 on 2021-08-28 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.FileField(upload_to='tracks_photos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
    ]
