# Generated by Django 3.2.7 on 2021-10-06 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(default='default_avatar.png', upload_to='projects_photos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_document',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='technical_document',
            field=models.TextField(),
        ),
    ]
