# Generated by Django 3.2.6 on 2021-08-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
    ]
