# Generated by Django 3.2.6 on 2021-08-28 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_track_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descirption', models.TextField()),
                ('link', models.TextField()),
                ('image', models.FileField(upload_to='resources_photos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])])),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='courses_photos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.FileField(upload_to='topics_photos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.course'),
        ),
    ]
