# Generated by Django 3.2.6 on 2021-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20210928_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrackbridge',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
