# Generated by Django 3.2.6 on 2021-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Infrastructure Engineer', 'Infrastructure Engineer'), ('Data Scientist', 'Data Scientist')], default='Software Engineer', max_length=50),
        ),
    ]
