# Generated by Django 3.2.6 on 2021-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Full-Stack', 'Full-Stack'), ('Front-End', 'Front-End'), ('Software Engineer', 'Software Engineer'), ('Infrastructure Engineer', 'Infrastructure Engineer')], default='Software Engineer', max_length=50),
        ),
    ]
