# Generated by Django 3.2.6 on 2021-08-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50)),
                ('resource_descirption', models.TextField()),
                ('resource_link', models.TextField()),
                ('resource_image', models.ImageField(upload_to='resources_photos')),
                ('resource_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.course')),
            ],
        ),
    ]
