# Generated by Django 3.2.6 on 2021-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='user_photos/'),
        ),
    ]
